import { getSession } from "next-auth/react";
import Head from "next/head";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
import { collection } from "firebase/firestore";
import { database } from "../firebase";

export default function Home({ session }) {
  if (!session) return <Login />;
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className="flex">
        <Sidebar />
        <Feed />
        <Widgets />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  // const posts = await collection(database, "posts");
  // const docs = posts.docs.map((post) => ({
  //   id: post.id,
  //   ...post.data(),
  //   timestamp: null,
  // }));
  return {
    props: {
      session,
      // posts: docs,
    },
  };
}
